### ISSUE TITLE
aws-gate install via PyPI is broken on Linux

### ISSUE THREAD

**Issue by alanjds** [xen0l/aws-gate#17]
Maybe  `requirements/*` is missing from MANIFEST.in on the published PyPI package
```
Collecting aws-gate==0.3.0 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/75/aa/3afcc4c7f2eea7e5c409cc265d7b0fd9f2ad9b59cdb28aa3f06bd205a221/aws-gate-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fbxF6Y/aws-gate/setup.py", line 31, in <module>
        install_requires=get_install_requirements('requirements/requirements.txt'),
      File "/tmp/pip-install-fbxF6Y/aws-gate/setup.py", line 13, in get_install_requirements
        with open(os.path.join(__location__, path), 'r') as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-fbxF6Y/aws-gate/requirements/requirements.txt'
```

**Comment by alanjds** [comment]
Closing the issue:

I was doing it on a docker image with Python 2.7. My bad.
No interest in maintaining 2.7 compatibility.
